### ISSUE TITLE
e2pv.php script throws error with PHP 8

### ISSUE THREAD

**Issue by jakenl** [omoerbeek/e2pv#10]
I'm a happy user from the moment that the Enecsys servers went down. As of 2 days ago the script doesn't run anymore. I realized that this started with updating of PHP from PHP 7.4 to PHP 8.

My line 390 might be different, so I will put the corresponding lines below.

PHP Fatal error:  Uncaught Error: Object of class Socket could not be converted to string in /home/pi/enecsys/e2pv.php:390
Stack trace:
#0 /home/pi/enecsys/e2pv.php(448): loop()
#1 {main}
  thrown in /home/pi/enecsys/e2pv.php on line 390

My e2pv.php lines (it is both line 390 and 391 (according https://phpstan.org/ the problem is on both lines):
$selarray[(string)$client] = $client;
$connections[(string)$client] = $conn;

phpstan also mentions the following when I check the script:
Cannot cast Socket to string. (line 390)
Cannot cast Socket to string. (line 391)

(when I start the script with PHP 7.4, it runs as it used to and the gateway connects directly)

**Comment by Marcel030nl** [comment]
hi @jakenl I have the same issue (now). Also very please with this script but now it's broken.

`marcel@purk:~$ php e2pv/e2pv.php 
PHP Fatal error:  Uncaught Error: Object of class Socket could not be converted to string in /home/marcel/e2pv/e2pv.php:372
Stack trace:
#0 /home/marcel/e2pv/e2pv.php(430): loop()
#1 {main}
  thrown in /home/marcel/e2pv/e2pv.php on line 372
marcel@purk:~$ php -version
PHP 8.1.2 (cli) (built: Jul 21 2022 12:10:37) (NTS)`

Any suggestions?
