### ISSUE TITLE
Address already in use.

### ISSUE THREAD

**Issue by Zandor300** [omoerbeek/e2pv#7]
Hi,

I'm trying out this script you wrote so (when it works) we can deploy this on all installations that are deployed by our company. But I'm getting some errors with it.  It points to line 306 on my modified version:
```php
$ok = socket_bind($socket, '0.0.0.0', 5040);
```

The only thing I added is some things to the MySQL statement's which shouldn't interfere with this function. But to be save, here is my modified version http://pastebin.com/f6ktRxd2 and here the config http://pastebin.com/7x6jjGrD

Also when I just manually run this script I notice it won't stop and let me run another command (if you know what I mean) and when I run ```sudo netstat -a -p -n``` it shows the socket 0.0.0.0:5040 is still open.

Hope you can help me with this...

-Zandor Smith

PS Nederland ftw!

**Comment by Zandor300** [comment]
Oh nvm,

Just noticed how the script should really work... :/ My bad!

**Comment by Zandor300** [comment]
But it still doesn't work... It won't display anything on pvoutput.org and it doesn't output anything into the log.

**Comment by omoerbeek** [comment]
On Tue, Jul 07, 2015 at 11:16:54PM -0700, Zandor Smith wrote:

> But it still doesn't work... It won't display anything on pvoutput.org and it doesn't output anything into the log.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/omoerbeek/e2pv/issues/7#issuecomment-119450912

I'm sorry, but I am not able to help you debug your configuration. The
only thing I can suggest is to check if logging is enabled and go from
there. See the README

	-Otto

**Comment by Zandor300** [comment]
I think I found the problem. I didn't set the Enecsys Gateway to post to the pi instead of the Enecsys servers. I think if I do that it will fix it but can't test it right now because the system is somewhere else... I will look if I can setup a SSH tunnel so I can get into the network.
