### ISSUE TITLE
Split inverter data in MySQL database

### ISSUE THREAD

**Issue by Zandor300** [omoerbeek/e2pv#8]
Is it possible to split the inverter data to the MySQL table? Like so:

Inverter | Data | Time
----------|--------|--------|
111111 | 10kWh | 10:30
222222 | 11kWh | 10:30
333333 | 12kWh | 10:30
111111 | 11kWh | 10:40
222222 | 12kWh | 10:40
333333 | 13kWh | 10:40

Thank you

**Comment by omoerbeek** [comment]
On Fri, Jul 10, 2015 at 12:31:02AM -0700, Zandor Smith wrote:

> Is it possible to split the inverter data to the MySQL table? Like so:
> 
> Inverter ID     DATA      DATE
> 111111          10kWh    1
> 222222          11kWh    1
> 333333          12kWh    1
> 111111          11kWh    2
> 222222          12kWh    2
> 333333          13kWh    2

That's already being done iirc.

	-Otto

**Comment by Zandor300** [comment]
But I don't want it to be splitted at PVOutput. Just in the MySQL table.

**Comment by omoerbeek** [comment]
On Sun, Jul 12, 2015 at 10:40:14PM -0700, Zandor Smith wrote:

> But I don't want it to be splitted at PVOutput. Just in the MySQL table.

It already does what you want in AGGREGATE mode: both individual and
aggregated values are sent to mysql.

	-Otto

**Comment by Zandor300** [comment]
Is id 0 when sending aggregated values?

 

Van: Otto Moerbeek [mailto:notifications@github.com] 
Verzonden: maandag 13 juli 2015 08:09
Aan: omoerbeek/e2pv
CC: Zandor Smith
Onderwerp: Re: [e2pv] Split inverter data in MySQL database (#8)

 

On Sun, Jul 12, 2015 at 10:40:14PM -0700, Zandor Smith wrote:

> But I don't want it to be splitted at PVOutput. Just in the MySQL table.

It already does what you want in AGGREGATE mode: both individual and
aggregated values are sent to mysql.

-Otto

**Comment by omoerbeek** [comment]
yes, iirc. But check the code...

	-Otto

**Comment by Zandor300** [comment]
Can I send values to the database every 10 minutes instead of every time the gateway pushes because in 24 hours I got 8000 records in my database and I need to log some 20 installations and that was just one...

**Comment by omoerbeek** [comment]
Currently the script sends all incoming data to mysql if a mysql db is
defined.  This was made to allow other postprocessing than PVOutput. I
do not have plans to change that,

	-Otto
